page:
  name: page
  in: query
  schema:
    type: integer
    minimum: 1
    default: 1
  description: 頁碼 (從 1 開始)

page_size:
  name: page_size
  in: query
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
  description: 每頁顯示筆數

sort:
  name: sort
  in: query
  schema:
    type: string
  description: 排序欄位 (例如：created_at, -created_at, email)
