page:
  name: page
  in: query
  schema:
    type: integer
    minimum: 1
    default: 1
  description: 頁碼 (從 1 開始)

page_size:
  name: page_size
  in: query
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
  description: 每頁顯示筆數

sort_by:
  name: sort_by
  in: query
  schema:
    type: string
  description: 排序欄位

sort_order:
  name: sort_order
  in: query
  schema:
    type: string
    enum: [ASC, DESC]
    default: DESC
  description: 排序方向 (預設 DESC)
